permalink:    /:year/:month/:day/:title/
#syntax_highlighter: rouge
paginate:     10
images:       /images
name: Roundcrisis
description: roundcrisis's adventures in code.
url: http://roundcrisis.com
highlighter: pygments
