markdown: redcarpet
permalink:    /:year/:month/:day/:title/
pygments:     true
paginate:     10
images:       /images

name: Roundcrisis
description: Rambling of mostly technical nature
url: http://hadihariri.com