permalink:    /:year/:month/:day/:title/
paginate:     10
images:       /images
name: Roundcrisis
title: Roundcrisis
description: roundcrisis's adventures in code.
url: http://roundcrisis.com
plugins:
  - jekyll-feed
defaults:
  - scope:
      type: categories  # select all category pages
    values:
      layout: category_page
      permalink: categories/:category/  