markdown: redcarpet
permalink:    /:year/:month/:day/:title/
highlighter:	pygments
paginate:     10
images:       /images
name: Roundcrisis
description: Something something something dark code
url: http://roundcrisis.com
